import * as vscode from 'vscode';
import { assertWorkspaceFilePath, validateWorkspaceRelativePath } from '../core/workspacePaths';
import { ToolRegistry } from './toolRegistry';
import { TerminalManager } from '../terminal/terminalManager';
import { prepareDevelopmentServerCommand } from '../terminal/developmentServerCommand';
import { createHash } from 'node:crypto';
import { RegisterToolOptions, ToolExecutionContext } from './toolRegistry';
import { packageInstallCommand } from './packageInstall';

export function registerProjectTools(registry: ToolRegistry, terminal?: TerminalManager): void {
  const register = (name: string, description: string, properties: Record<string, unknown>, required: string[], handler: (args: Record<string, unknown>, signal: AbortSignal, execution: ToolExecutionContext) => Promise<unknown>, options?: RegisterToolOptions) => registry.registerTool({ type: 'function', function: { name, description, parameters: { type: 'object', properties, required, additionalProperties: false } } }, (args, execution) => handler(args, execution.signal, execution), options);
  const root = () => { const folder = vscode.workspace.workspaceFolders?.[0]; if (!folder) throw new Error('Open a workspace folder first.'); return folder.uri; };
  const processes = () => { if (!terminal) throw new Error('The managed terminal service is unavailable.'); if (!vscode.workspace.isTrusted) throw new Error('Trust this workspace before executing processes.'); return terminal; };
  const text = (value: unknown, name: string) => { if (typeof value !== 'string' || !value.trim() || value.length > 1000 || /[\r\n\u0000]/.test(value)) throw new Error(`${name} must be a non-empty bounded single-line string.`); return value.trim(); };
  const packageBytes = async () => { const uri = vscode.Uri.joinPath(root(), 'package.json'); await assertWorkspaceFilePath(root().fsPath, uri.fsPath); const bytes = await vscode.workspace.fs.readFile(uri); if (bytes.byteLength > 512 * 1024) throw new Error('package.json exceeds 512 KiB.'); return bytes; };
  const packageInfo = async () => JSON.parse(new TextDecoder().decode(await packageBytes())) as { scripts?: Record<string, string>; dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
  const manifestHash = async () => createHash('sha256').update(await packageBytes()).digest('hex');
  const assertApprovedManifest = async (execution: ToolExecutionContext) => { if (execution.approvedArguments?.manifestHash !== await manifestHash()) throw new Error('package.json changed after approval. Inspect the changed scripts and request approval again; no command was started.'); };
  const prepareScript = (script: string) => async (args: Record<string, unknown>) => ({ ...args, command: await scriptCommand(script), manifestHash: await manifestHash(), expandedScripts: Object.fromEntries(Object.entries((await packageInfo()).scripts || {}).filter(([name]) => [script, `pre${script}`, `post${script}`].includes(name))) });
  const scriptCommand = async (script: string) => { const manifest = await packageInfo(); if (typeof manifest.scripts?.[script] !== 'string' || !manifest.scripts[script].trim()) throw new Error(`package.json has no ${script} script. Add a valid script using the file edit tools before retrying.`); return `npm run ${script}`; };
  register('create_directory', 'Create a workspace-relative directory, including missing parents. Explicit approval; not a reviewed file edit.', { path: { type: 'string' } }, ['path'], async (args, signal) => { const uri = vscode.Uri.joinPath(root(), ...validateWorkspaceRelativePath(text(args.path, 'path'))); await assertWorkspaceFilePath(root().fsPath, uri.fsPath, true); signal.throwIfAborted(); await vscode.workspace.fs.createDirectory(uri); return { success: true, path: args.path }; });
  register('file_stat', 'Check whether a workspace path exists and inspect its size/type without reading its content.', { path: { type: 'string' } }, ['path'], async (args) => { const uri = vscode.Uri.joinPath(root(), ...validateWorkspaceRelativePath(text(args.path, 'path'))); try { await assertWorkspaceFilePath(root().fsPath, uri.fsPath); const stat = await vscode.workspace.fs.stat(uri); return { path: args.path, exists: true, size: stat.size, type: stat.type, mtime: stat.mtime }; } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT' || (error as { code?: string }).code === 'FileNotFound') return { path: args.path, exists: false }; throw error; } });
  register('inspect_package_scripts', 'Inspect declared package scripts and dependency names. Does not execute package scripts.', {}, [], async () => { const manifest = await packageInfo(); return { scripts: manifest.scripts || {}, dependencies: manifest.dependencies || {}, devDependencies: manifest.devDependencies || {} }; });
  register('install_dependencies', 'Install dependencies declared in workspace package.json using npm install, or npm ci with a lockfile. Requires explicit command/network approval. Installation can execute package lifecycle scripts.', { locked: { type: 'boolean' } }, [], async (args, signal, execution) => { await assertApprovedManifest(execution); return processes().runCommand(args.locked ? 'npm ci' : 'npm install', root().fsPath, false, 300000, signal); }, { timeout: 330000, prepareApproval: async args => { if (args.locked !== undefined && typeof args.locked !== 'boolean') throw new Error('locked must be boolean.'); return { ...args, command: args.locked ? 'npm ci' : 'npm install', manifestHash: await manifestHash(), expandedScripts: (await packageInfo()).scripts || {} }; } });
  register('install_packages', 'Add missing registry packages to this workspace package.json and install them. packages accepts names with optional exact versions/tags; dev true saves build/test tooling in devDependencies. Explicit command/network approval is required; lifecycle scripts can execute. Inspect failures before retrying the original build.', { packages: { type: 'array', items: { type: 'string' }, minItems: 1, maxItems: 20 }, dev: { type: 'boolean' } }, ['packages'], async (args, signal, execution) => { await assertApprovedManifest(execution); const command = packageInstallCommand(args); if (execution.approvedArguments?.command !== command) throw new Error('Package installation differs from the approved command; no process was started.'); return processes().runCommand(command, root().fsPath, false, 300000, signal); }, { timeout: 330000, prepareApproval: async args => ({ ...args, command: packageInstallCommand(args), manifestHash: await manifestHash(), expandedScripts: (await packageInfo()).scripts || {} }) });
  for (const script of ['build', 'lint']) register(`run_${script}`, `Execute the declared npm ${script} script with explicit process approval. Missing scripts must be added to package.json, not guessed.`, {}, [], async (_args, signal, execution) => { await assertApprovedManifest(execution); return processes().runCommand(await scriptCommand(script), root().fsPath, false, 180000, signal); }, { timeout: 200000, prepareApproval: prepareScript(script) });
  register('start_dev_server', 'Start or reuse a tracked workspace localhost server. A plain Python http.server command is automatically bound to 127.0.0.1 before explicit approval. Other commands must specify loopback themselves. Use process_status and browser_action for readiness; stop_process before an intentional restart.', { command: { type: 'string', description: 'Server command, e.g. python3 -m http.server 8080 --bind 127.0.0.1. The exact command actually executed is shown for approval.' } }, ['command'], async (args, signal, execution) => { const command = prepareDevelopmentServerCommand(args.command); if (execution.approvedArguments?.command !== command) throw new Error('Development-server command differs from the approved command; no process was started.'); const record = await processes().startBackgroundCommand(command, root().fsPath, signal); if (record.status !== 'running') throw new Error(`Development server did not remain running (${record.status}, exit ${record.exitCode ?? 'unknown'}). ${record.stderr || record.stdout}`); return record; }, { prepareApproval: async args => ({ ...args, command: prepareDevelopmentServerCommand(args.command), requestedCommand: args.command }) });
  register('process_status', 'Inspect this agent terminal service’s tracked processes, commands, output, exit codes and status. Does not inspect other user processes.', { process_id: { type: 'string', description: 'Use the opaque id returned by start_dev_server (proc-...), NOT the numeric OS processId. Omit to inspect all owned processes.' } }, [], async (args) => { if (!terminal) throw new Error('The managed terminal service is unavailable.'); const records = terminal.getAllProcesses(); const found = args.process_id ? records.filter(record => record.id === text(args.process_id, 'process_id')) : records; if (args.process_id && !found.length) throw new Error(`Unknown tracked process ID. Use the returned id (proc-...), not numeric processId, or omit process_id. Available owned IDs: ${records.map(record => record.id).join(', ') || 'none'}.`); return found.map(record => ({ ...record, stdout: record.stdout.slice(-10000), stderr: record.stderr.slice(-5000) })); });
  register('stop_process', 'Stop only a process previously started and tracked by this agent, using its returned process_id. Requires explicit approval.', { process_id: { type: 'string', description: 'Opaque id returned by the agent process tool (proc-...), NOT a numeric OS processId.' } }, ['process_id'], async (args) => { const id = text(args.process_id, 'process_id'); const manager = processes(); if (!manager.getAllProcesses().some(record => record.id === id)) throw new Error('Unknown tracked process ID; no external process was stopped.'); return { process_id: id, stopRequested: manager.stopProcess(id) }; });
}
