const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { chromium } = require('playwright-core');
const { findBrowserExecutable } = require('../dist/browser/renderedBrowser');
async function main() {
  const output = path.resolve(process.argv[2] || 'ui-test-results');
  await fs.mkdir(output, { recursive: true });
  const child = spawn(process.execPath, [path.join(__dirname, 'preview-chat.cjs')], { stdio: ['ignore', 'pipe', 'pipe'] });
  let browser;
  const errors = [];
  const checks = [];
  try {
    const url = await new Promise((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('UI preview did not start')), 15000);
      child.on('error', reject);
      child.on('exit', code => { clearTimeout(timeout); reject(new Error('Preview exited: ' + code)); });
      child.stdout.on('data', chunk => {
        const match = String(chunk).match(/CHAT_UI_FIXTURE_URL=(http[^\s]+)/);
        if (match) { clearTimeout(timeout); resolve(match[1]); }
      });
    });
    browser = await chromium.launch({ executablePath: await findBrowserExecutable(), headless: true });
    const page = await browser.newPage();
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.goto(url);
    assert.equal(await page.locator('.header #modelSelect, .header #modeSelect').count(), 0);
    assert.equal(await page.locator('.composer #modelSelect, .composer #modeSelect, .composer #effortSelect, .composer #promptInput, .composer #sendBtn').count(), 5);
    assert.equal(await page.locator('#settingsDrawer #accessScopeSelect, #settingsDrawer .strategy-toggle').count(), 2);
    assert.equal(await page.locator('.mode-bar').count(), 0);
    assert.equal(await page.locator('.welcome').innerText().then(text => text.includes('What would you like to build?')), true);
    checks.push('New composer-first structure, no top model/mode bars, advanced controls only in settings');
    const emit = data => page.evaluate(payload => window.dispatchEvent(new MessageEvent('message', { data: payload })), data);
    const overflow = () => page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
    for (const effort of ['low', 'medium', 'high', 'ultra']) {
      await page.locator('#effortSelect').selectOption(effort);
      assert.deepEqual(await page.evaluate(() => window.__previewMessages.at(-1)), { type: 'setEffort', effort });
      await emit({ type: 'effort', effort });
      assert.equal(await page.locator('#effortSelect').inputValue(), effort);
    }
    checks.push('Four exact effort choices beside the model, with host-acknowledged values');
    for (const width of [280, 320, 375, 768, 1280]) {
      await page.setViewportSize({ width, height: 760 });
      assert.equal(await overflow(), false);
      assert.equal(await page.locator('.timeline-row').count(), 0, 'No seeded fake operations');
      await page.screenshot({ path: path.join(output, 'chat-' + width + '.png') });
      await page.locator('#settingsBtn').click();
      assert.equal(await overflow(), false);
      assert.equal(await page.locator('#settingsDrawer').evaluate(element => element.scrollHeight > element.clientHeight), true);
      assert.equal(await page.locator('.header').evaluate(element => element.inert), true);
      await page.locator('#settingsDrawer').press('Escape');
      assert.equal(await page.locator('#settingsBtn').evaluate(element => document.activeElement === element), true);
      checks.push('Layout, settings scrolling and focus restore at ' + width);
    }
    await emit({ type: 'models', selectedModel: 'auto', models: [{ id: 'ssh-gpu:coder', displayName: 'GPU coder', providerId: 'ssh-gpu', source: 'remote' }, { id: 'api:coder', displayName: 'API coder', source: 'api' }] });
    assert.equal(await page.locator('#activeModelBadge').innerText(), 'Auto');
    await page.locator('#modelSelect').selectOption('ssh-gpu:coder');
    assert.equal(await page.locator('#activeModelBadge').innerText(), 'Remote');
    await page.locator('#modeSelect').selectOption('ask');
    assert.equal(await page.evaluate(() => window.__previewMessages.at(-1).mode), 'ask');
    await page.locator('#modeSelect').selectOption('plan');
    assert.equal(await page.evaluate(() => window.__previewMessages.at(-1).mode), 'plan');
    await emit({ type: 'mode', mode: 'agent' });
    assert.equal(await page.locator('#modeSelect').inputValue(), 'agent');
    const files = ['src/my component.ts', ...Array.from({ length: 10 }, (_, index) => 'src/file-' + index + '.ts')];
    await page.locator('#filePicker summary').click();
    await emit({ type: 'contextFiles', files });
    await page.getByLabel('src/my component.ts', { exact: true }).focus();
    await page.evaluate(() => { window.__originalFileNode = document.querySelector('#fileList input'); });
    await page.getByLabel('src/my component.ts', { exact: true }).check();
    assert.equal(await page.evaluate(() => document.activeElement === window.__originalFileNode && window.__originalFileNode.isConnected), true, 'Selecting a file must preserve its node and keyboard focus');
    for (const file of files.slice(1, 10)) await page.getByLabel(file, { exact: true }).check();
    assert.equal(await page.getByLabel(files[10], { exact: true }).isDisabled(), true);
    await page.locator('#filePicker summary').click();
    await page.locator('#promptInput').fill('Summarize these selected files');
    await page.locator('#sendBtn').click();
    const sent = await page.evaluate(() => window.__previewMessages.filter(message => message.type === 'chat'));
    assert.equal(sent.length, 1);
    assert.deepEqual(sent[0].files, files.slice(0, 10));
    assert.equal(sent[0].model, 'ssh-gpu:coder');
    assert.equal(await page.locator('#modelSelect').isEnabled(), true, 'Terminal errors release model controls');
    await emit({ type: 'status', state: 'running', message: 'Real generation metadata fixture' });
    assert.equal(await page.locator('#modelSelect').isDisabled(), true);
    assert.equal(await page.locator('#modeSelect').isDisabled(), true);
    assert.equal(await page.locator('#effortSelect').isDisabled(), true);
    await emit({ type: 'controlError', message: 'Wait for the task before changing effort.' });
    assert.equal(await page.locator('#modelSelect').isDisabled(), true, 'Control failures must not unlock a running task');
    assert.equal(await page.locator('#effortSelect').isDisabled(), true);
    await emit({ type: 'done', fullResponse: '```markdown\n## UI regression fixture\n- **Formatted** content\n\n<script>alert(1)</script>\n```' });
    assert.equal(await page.locator('#modelSelect').isEnabled(), true);
    assert.equal(await page.locator('.msg-assistant h2').count(), 1);
    assert.equal(await page.locator('.msg-assistant pre').count(), 0, 'Whole-reply Markdown must render as headings and lists, not as a code listing');
    assert.equal(await page.locator('.msg-assistant script').count(), 0);
    await page.locator('#filePicker summary').click();
    await page.locator('#fileFilter').press('Escape');
    assert.equal(await page.locator('#filePicker').evaluate(element => element.open), false);
    assert.equal(await page.locator('#filePicker summary').evaluate(element => document.activeElement === element), true);
    await page.locator('#filePicker summary').click();
    await page.locator('#chatHistory summary').click();
    assert.equal(await page.locator('#filePicker').evaluate(element => element.open), false);
    await page.locator('#promptInput').click();
    assert.equal(await page.locator('#chatHistory').evaluate(element => element.open), false);
    checks.push('Selection preserves keyboard focus; Escape/outside click dismiss popovers; popovers are mutually exclusive');
    await emit({ type: 'status', state: 'running', message: 'Controlled approval fixture, not model execution' });
    const decisions = [['allow', 'allow'], ['deny', 'deny'], ['allow-session', 'allow_session']];
    for (const [button, decision] of decisions) {
      const requestId = 'fixture-' + decision;
      const before = await page.evaluate(() => window.__previewMessages.length);
      await emit({ type: 'permissionRequest', request: { id: requestId, description: 'Controlled approval fixture', command: 'node --test fixture.test.cjs', workspaceSessionAvailable: true } });
      await page.locator('#' + button + '-' + requestId).click();
      const messages = await page.evaluate(start => window.__previewMessages.slice(start), before);
      assert.deepEqual(messages, [{ type: 'permissionResolved', requestId, decision }]);
      assert.equal(await page.locator('#perm-' + requestId).count(), 1, 'Keep the approval visible until the real host acknowledges it');
      assert.equal(await page.locator('#' + button + '-' + requestId).isDisabled(), true);
      assert.equal(await page.locator('#modelSelect').isDisabled(), true, 'Approval must not unlock or cancel the running task');
      await emit({ type: 'permissionDecision', requestId, decision });
      assert.equal(await page.locator('#perm-' + requestId).count(), 0);
    }
    checks.push('Allow, Deny and session buttons post only their exact decision, never cancel; cards await host acknowledgement');
    await emit({ type: 'contextFiles', files: Array.from({ length: 1000 }, (_, index) => 'stress/file-' + index + '.ts') });
    await emit({ type: 'status', state: 'running', message: 'Controlled stress fixture, not model execution' });
    const load = await page.evaluate(() => {
      const fileNode = document.querySelector('#fileList input');
      let fileMutations = 0;
      let streamMutations = 0;
      const observer = new MutationObserver(records => {
        fileMutations += records.filter(record => record.target.closest?.('#fileList')).length;
        streamMutations += records.filter(record => record.target.closest?.('.streaming')).length;
      });
      observer.observe(document.querySelector('#fileList'), { childList: true, subtree: true });
      observer.observe(document.querySelector('#mainScroll'), { childList: true, subtree: true });
      const started = performance.now();
      for (let index = 0; index < 500; index += 1) window.dispatchEvent(new MessageEvent('message', { data: { type: 'chunk', content: 'token-' + index + ' ' } }));
      for (let index = 0; index < 100; index += 1) window.dispatchEvent(new MessageEvent('message', { data: { type: 'activity', activity: { id: 'load-' + index, title: 'Controlled activity ' + index, status: 'success' } } }));
      return new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(() => {
        observer.disconnect();
        resolve({ elapsedMilliseconds: performance.now() - started, files: document.querySelectorAll('#fileList input').length, fileNodePreserved: fileNode === document.querySelector('#fileList input'), fileMutations, streamMutations, streamComplete: document.querySelector('.streaming')?.textContent.includes('token-499') });
      })));
    });
    assert.equal(load.files, 1000);
    assert.equal(load.fileNodePreserved, true);
    assert.equal(load.fileMutations, 0, 'Stream/status updates must not rebuild the file picker');
    assert.equal(load.streamComplete, true);
    assert.ok(load.streamMutations <= 2, 'Burst token rendering should be coalesced per animation frame');
    assert.equal(await page.locator('[id^="act-row-load-"]').count(), 100);
    assert.equal(await overflow(), false);
    await page.locator('#sendBtn').click();
    assert.equal(await page.locator('#sendBtn').innerText(), 'Stopping…');
    assert.equal(await page.locator('#sendBtn').isDisabled(), true);
    assert.equal(await page.locator('#modeSelect').isDisabled(), true);
    await page.locator('#promptInput').press('Escape');
    assert.equal(await page.evaluate(() => window.__previewMessages.filter(message => message.type === 'cancel').length), 1);
    await emit({ type: 'status', state: 'running', message: 'Finishing cancellation' });
    assert.equal(await page.locator('#sendBtn').isDisabled(), true);
    await emit({ type: 'status', state: 'ready', message: 'Cancelled' });
    assert.equal(await page.locator('#sendBtn').isEnabled(), true);
    assert.equal(await page.locator('#modeSelect').isEnabled(), true);
    checks.push({ check: '1000 files, 500 streamed tokens, 100 activity rows; no file DOM churn; coalesced stream; cancellation locked until host acknowledgement', load });
    await page.setViewportSize({ width: 375, height: 760 });
    await page.screenshot({ path: path.join(output, 'conversation-375.png') });
    await page.locator('#settingsBtn').click();
    await page.locator('#openModelsBtn').click();
    assert.equal(await page.evaluate(() => window.__previewMessages.at(-1).type), 'openModels');
    await page.locator('#settingsDrawer').press('Escape');
    await page.addStyleTag({ content: ':root { --vscode-sideBar-background:#fafafa; --vscode-foreground:#202124; --vscode-descriptionForeground:#60646c; --vscode-input-background:#eee; --vscode-input-foreground:#202124; --vscode-panel-border:#ddd; --vscode-editor-background:#fff; }' });
    await page.setViewportSize({ width: 320, height: 760 });
    assert.equal(await overflow(), false);
    await page.screenshot({ path: path.join(output, 'chat-light-320.png') });
    await page.goto(url + '/models');
    await emit({ type: 'downloadTargets', targets: [{ id: 'ollama', label: 'This machine' }, { id: 'ssh-gpu', label: 'SSH GPU host' }] });
    assert.deepEqual(errors, [], 'Model Center script must start without CSP or JavaScript errors');
    assert.equal(await page.locator('#downloadTarget option').count(), 2, 'The real message listener must render both destinations');
    await page.locator('#downloadTarget').selectOption('ssh-gpu');
    await page.locator('#modelName').fill('coder:test');
    await page.locator('#install').click();
    assert.deepEqual(await page.evaluate(() => window.__previewMessages.at(-1)), { type: 'installModel', model: 'coder:test', targetId: 'ssh-gpu' });
    await emit({ type: 'modelCenterStatus', state: 'paused', model: 'coder:test', targetId: 'ssh-gpu' });
    assert.equal(await page.locator('#downloadTarget').isDisabled(), true);
    assert.equal(await page.locator('#install').innerText(), 'Resume download');
    await page.locator('#install').click();
    assert.equal(await page.evaluate(() => window.__previewMessages.at(-1).targetId), 'ssh-gpu');
    await emit({ type: 'modelCenterStatus', state: 'complete', model: 'coder:test', targetId: 'ssh-gpu', message: 'Controlled fixture complete, no download executed' });
    assert.equal(await page.locator('#downloadTarget').isEnabled(), true);
    assert.equal(await overflow(), false);
    await page.screenshot({ path: path.join(output, 'models-320.png') });
    checks.push('Model Center exact SSH target payload, pause/resume target pinning, completion releases controls, 320px layout');
    checks.push('Exact model selection, real file payload including spaces, ten-file bound, mode toggles, busy/error recovery, sanitized markdown, model management entry point, light theme');
    assert.deepEqual(errors, []);
    await fs.writeFile(path.join(output, 'result.json'), JSON.stringify({ passed: true, kind: 'Controlled UI fixture, NOT model execution or website acceptance', checks, errors }, null, 2));
    console.log('CHAT_UI_CHECKS_PASSED ' + output);
  } finally { await browser?.close(); child.kill(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
